substitutions:
  _REDIS_URL: "redis://10.99.152.92:6379"

steps:

  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "gcr.io/$PROJECT_ID/simple-nuxt-redis:$SHORT_SHA",
        ".",
      ]
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/simple-nuxt-redis:$SHORT_SHA"]

  - name: "gcr.io/cloud-builders/gcloud"
    args: [
        "run",
        "deploy",
        "simple-nuxt-redis",
        "--image",
        "gcr.io/$PROJECT_ID/simple-nuxt-redis:$SHORT_SHA",
        "--update-env-vars",
        "REDIS_URL=${_REDIS_URL}",
        "--platform",
        "managed",
        "--memory=1G",
        "--region",
        "europe-west3",
        "--vpc-connector",
        "my-vpc-connector",
        "--allow-unauthenticated",
      ]
timeout: "1600s"

