steps:
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: "bash"
    args:
    - "-c"
    - |
      REDIS_IP=$(gcloud redis instances describe my-redis-cache --region=europe-west3 --format='value(host)')
      echo "REDIS_URL=redis://$REDIS_IP:6379" >> $$GITHUB_ENV

  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "gcr.io/$PROJECT_ID/simple-nuxt-redis:1.1",
        ".",
      ]
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/simple-nuxt-redis:1.1"]

  - name: "gcr.io/cloud-builders/gcloud"
    args: [
        "run",
        "deploy",
        "vuestorefront-demo-site-1",
        "--image",
        # "gcr.io/$PROJECT_ID/simple-nuxt-redis:$BUILD_ID",
        "gcr.io/$PROJECT_ID/simple-nuxt-redis:1.1",
        "--update-env-vars",
        "REDIS_URL=$REDIS_URL",
        "--platform",
        "managed",
        "--memory=1G",
        "--region",
        "europe-west3",
        "--vpc-connector",
        "my-vpc-connector",
        "--allow-unauthenticated",
      ]
timeout: "1600s"
